version: "3"

services:
  api:
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - ".:/app"
    command: pipenv run python prod.py

  mongo:
    image: mongo:latest
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    expose:
      - 27017
    command: mongod
