name: Release
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: 🏁 Checkout
        uses: actions/checkout@v2

      - name: ✅ Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: 💿 Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: 📦 Install dependencies
        run: poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

      - name: 🧪 Run tests
        run: |
          poetry run poe alltest

  Release:
    needs: [Test]
    runs-on: ubuntu-latest
    steps:
      - name: 🏁 Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
          persist-credentials: false

      - name: ✅ Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: 💿 Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: 📦 Install dependencies
        run: poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

      - name: 🏷 Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: ⬆️ Update package version
        run: |
          poetry version $(git describe --tags --abbrev=0)

      - name: ➕ Commit files
        run: |
          git config --local user.email "jan.philip.wahle@gmail.com"
          git config --local user.name "github-actions[bot]"
          git add pyproject.toml
          git commit -m "[release-bot] Update pyproject.toml version"

      - name: 💨 Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: ${{ github.ref }}

      - name: 🔨 Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
          generateReleaseNotes: true
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: 🔑 Docker GitHub package login
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: 🐳 Build docker image
        run: docker build -t ghcr.io/gipplab/cs-insights-prediction-endpoint:${{steps.tagging.outputs.tag}} -t ghcr.io/gipplab/cs-insights-prediction-endpoint:latest .

      - name: 📦 Push docker image
        run: |
          docker push ghcr.io/gipplab/cs-insights-prediction-endpoint:${{steps.tagging.outputs.tag}}
          docker push ghcr.io/gipplab/cs-insights-prediction-endpoint:latest

  Coverage:
    needs: [Test]
    runs-on: ubuntu-latest
    steps:
      - name: 🏁 Checkout
        uses: actions/checkout@v2

      - name: ✅ Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: 💿 Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: 📦 Install dependencies
        run: poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

      - name: 🧪 Run tests
        run: |
          poetry run poe alltest

      - name: ⬆ Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml

  Docs:
    needs: [Test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: 💿 Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: 📦 Install dependencies
        run: poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

      - name: 📘 Generate docs
        run: |
          poetry run poe doc

      - name: 🚀 Deploy docs
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: docs
          folder: ./docs
